#!/usr/bin/env bash
#MISE description="Gets the number of lines of TypeScript code in the project"

set -euxo pipefail

nroflines=$(fd -Iitf -e ts -e tsx -E node_modules -x cat | wc -l)

printf "Lines of TypeScript powering this website: %d\n" "$nroflines"

# Set in mise environment (available to subsequent mise run commands)
mise set NEXT_PUBLIC_NUMBER_OF_LINES="${nroflines}"
